Notes for flipped images error
Error occured with the added flipped images code. Code from the lectures

TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:
ValueError: setting an array element with a sequence.